# Generated by Django 5.0.2 on 2024-03-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
