# Generated by Django 5.0.2 on 2024-03-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0002_alter_tour_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
