# Generated by Django 5.0.2 on 2024-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0006_alter_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
