# Generated by Django 5.0.2 on 2024-03-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0008_alter_excursion_options_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={},
        ),
        migrations.AddField(
            model_name='client',
            name='password1',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='password2',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
