# Generated by Django 5.0.2 on 2024-03-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0010_remove_order_client_remove_question_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourorder',
            name='end_date',
        ),
    ]
