# Generated by Django 5.0.2 on 2024-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0013_alter_hotel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
