# Generated by Django 5.0.2 on 2024-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0017_excursion_excursion_image_excursion_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='transpont',
            name='transport_type',
            field=models.CharField(choices=[('BUS', 'Автобус'), ('TRAIN', 'Поїзд')], max_length=10),
        ),
    ]
